version: '3'
services:
  backend:
    image: daikonk/sm-backend:latest
    container_name: "sm-backend"
    ports:
      - "3000:3000"
    
  frontend:
    image: daikonk/sm-frontend:latest
    container_name: "sm-frontend"
    