FROM python:3
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . /backend
WORKDIR /backend/

EXPOSE 8000

ENTRYPOINT [ "python", "backend/manage.py" ]
CMD [ "runserver", "0.0.0.0:8000" ]