# Generated by Django 4.2.7 on 2023-12-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('members', models.IntegerField(default=0)),
                ('date', models.CharField(max_length=200)),
            ],
        ),
    ]
