# Generated by Django 4.2.7 on 2023-12-03 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportEvent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportevent',
            old_name='date',
            new_name='eventname',
        ),
        migrations.RemoveField(
            model_name='sportevent',
            name='name',
        ),
    ]
