# Generated by Django 4.2.7 on 2023-12-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportEvent', '0003_sportevent_datetime_sportevent_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportevent',
            name='datetime',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='sportevent',
            name='eventname',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='sportevent',
            name='firstname',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='sportevent',
            name='info',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='sportevent',
            name='lastname',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='sportevent',
            name='location_address',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='sportevent',
            name='location_city',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='sportevent',
            name='location_state',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='sportevent',
            name='location_zip',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='sportevent',
            name='phonenum',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
