# Generated by Django 4.2.7 on 2023-12-03 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportEvent', '0005_alter_sportevent_datetime_alter_sportevent_eventname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportevent',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='sportevent',
            name='info',
        ),
        migrations.RemoveField(
            model_name='sportevent',
            name='phonenum',
        ),
    ]
