# Generated by Django 4.2.7 on 2023-12-03 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportEvent', '0006_remove_sportevent_datetime_remove_sportevent_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportevent',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='sportevent',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='sportevent',
            name='location_address',
        ),
        migrations.RemoveField(
            model_name='sportevent',
            name='location_city',
        ),
        migrations.RemoveField(
            model_name='sportevent',
            name='location_state',
        ),
        migrations.RemoveField(
            model_name='sportevent',
            name='location_zip',
        ),
    ]
