# Generated by Django 4.2.7 on 2023-12-03 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SportEvent', '0008_sportevent_firstname_sportevent_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportevent',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportevent',
            name='info',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportevent',
            name='phonenum',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
