# Generated by Django 4.2.7 on 2023-12-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportEvent', '0009_sportevent_datetime_sportevent_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportevent',
            name='datetime',
        ),
    ]
