# Generated by Django 4.2.7 on 2023-12-03 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SportEvent', '0011_sportevent_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportevent',
            name='skill',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
