# Generated by Django 4.2.7 on 2023-12-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportEvent', '0012_sportevent_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportevent',
            name='info',
            field=models.TextField(default=''),
        ),
    ]
