# Generated by Django 4.2.7 on 2023-12-03 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportEvent', '0017_alter_sportevent_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportevent',
            name='info',
        ),
    ]
