# Generated by Django 4.2.7 on 2023-12-03 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SportEvent', '0018_remove_sportevent_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportevent',
            name='info',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
