# Generated by Django 4.2.7 on 2023-12-10 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportEvent', '0023_sportevent_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='sportevent',
            name='user',
        ),
    ]
