# Generated by Django 4.2.7 on 2023-12-10 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportEvent', '0026_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_num',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sport',
        ),
    ]
