# Generated by Django 4.2.7 on 2023-12-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportEvent', '0028_userprofile_age_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='./profile_pictures/'),
        ),
    ]
