# Generated by Django 4.2.7 on 2023-12-11 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportEvent', '0031_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_picture',
            new_name='profile_pic',
        ),
    ]
