name: Docker Image CD

on:
  workflow_run:
    workflows: [ "Docker Image CI" ]
    types:
      - completed
    

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: pull sm-frontend
      run: docker pull daikonk/sm-frontend:latest

    - name: pull sm-backend
      run: docker pull daikonk/sm-backend:latest

    - name: pull sm-worker
      run: docker pull daikonk/sm-worker:latest

    - name: docker compose up
      run: docker-compose up
    
